version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/validate.sh
      timeout: 30
      runas: ubuntu